In [2]:
import os
import PIL
import cv2
import scipy
import pathlib
import numpy as np
import tensorflow as tf
import PIL.Image as Image
import tqdm as notebook_tqdm
import tensorflow_datasets as tfds
from matplotlib import pyplot as plt

In [10]:
dataset_folder = "..\\archive"  

defect_images_folder = os.path.join(dataset_folder, "Defect_images\\*")
defect_files_ds = tf.data.Dataset.list_files(defect_images_folder, shuffle = 'False')

mask_images_folder = os.path.join(dataset_folder, "Mask_images")

# flatten no defect folder  
no_defect_images_folder = os.path.join(dataset_folder, "NODefect_images")
no_defect_files_ds = tf.data.Dataset.list_files(no_defect_images_folder, shuffle = 'False')


len(defect_files_ds)
len(no_defect_files_ds)

1

In [4]:
print(len(defect_files_ds))

106


In [8]:
def get_labels(file_path):
    file_name = tf.strings.split(file_path, sep='\\')[-1]
    image_code = tf.strings.split(file_name, sep='_')

    index_code = image_code[0]
    index = tf.strings.to_number(
        index_code,
        tf.int32
    )

    defect_code = image_code[1]
    defect_type = tf.strings.to_number(
        defect_code,
        tf.int32
    )

    fabric_code = tf.strings.split(image_code[2], sep='.')[0]
    fabric_type = tf.strings.to_number(
        fabric_code,
        tf.int32
    )
    
    return index, defect_type, fabric_type

def process_img(file_path):
    index, defect_type, fabric_type = get_labels(file_path)
    img = tf.io.read_file(file_path)
    img = tf.io.decode_png(img)
    
    return img, index, defect_type, fabric_type

a = defect_files_ds.map(process_img)

In [7]:
b = defect_files_ds.take(1)
for i in b:
    print(i)

tf.Tensor(b'..\\archive\\Defect_images\\0098_019_02.png', shape=(), dtype=string)


In [9]:
b = a.take(1)
for i in b:
    print(i)

(<tf.Tensor: shape=(256, 4096, 1), dtype=uint8, numpy=
array([[[255],
        [255],
        [255],
        ...,
        [143],
        [141],
        [127]],

       [[255],
        [255],
        [255],
        ...,
        [163],
        [153],
        [142]],

       [[255],
        [255],
        [255],
        ...,
        [151],
        [156],
        [150]],

       ...,

       [[255],
        [255],
        [255],
        ...,
        [146],
        [134],
        [123]],

       [[255],
        [255],
        [255],
        ...,
        [140],
        [139],
        [127]],

       [[255],
        [255],
        [255],
        ...,
        [132],
        [137],
        [127]]], dtype=uint8)>, <tf.Tensor: shape=(), dtype=int32, numpy=39>, <tf.Tensor: shape=(), dtype=int32, numpy=19>, <tf.Tensor: shape=(), dtype=int32, numpy=2>)


In [ ]:
# Defect codes
DEFECT_CODES = {
    0:  'No defect',
    2:	'Broken end',
    6:	'Broken yarn',
    10:	'Broken pick',
    16:	'Weft curling',
    19:	'Fuzzyball',
    22:	'Cut selvage',
    23:	'Crease',
    25:	'Warp ball',
    27:	'Knots',
    29:	'Contamination',
    30:	'Nep',
    36:	'Weft crack'
}



In [ ]:
len(defect_files_ds)

In [ ]:
img = Image.open("..\\archive\\Defect_images\\0003_002_00.png")
img

In [ ]:
img_gen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255, rotation_range=20)
images, labels = next(img_gen.flow_from_directory(dataset_folder))

In [ ]:
print(images.dtype, images.shape)
print(labels.dtype, labels.shape)

In [ ]:
image_ds = tf.data.Dataset.list_files(defect_images_folder, shuffle = 'False')
# view the files
for i in image_ds.take(5):
    print(i.numpy())

Feature Engineering

Supervised Learning

Unsupervised or Semisupervised Learning

Model Deployment/Evaluation